### ISSUE TITLE
Contribute syntaxes to Metals question

### ISSUE THREAD

**Issue by Arthurm1** [mnxn/vscode-jvm-bytecode-viewer#2]
It looks as though you've put a lot of effort into constructing the syntaxes for javap output.  They make a huge difference to the readability of the output.

I was wondering if you'd care to contribute the 2 jvm-bytecode syntaxes you've developed to [Metals](https://github.com/scalameta/metals-vscode) (a Java/Scala LSP) or if you minded if I submitted a PR copying them?

Metals has a way to view javap output currently but without any highlighting and your syntaxes would greatly improve that area.

**Comment by mnxn** [comment]
> I was wondering if you'd care to contribute the 2 jvm-bytecode syntaxes you've developed to Metals (a Java/Scala LSP) or if you minded if I submitted a PR copying them?

I unfortunately do not currently have time to submit it myself, but you are allowed to copy it if you follow the terms of the license:

https://github.com/mnxn/vscode-jvm-bytecode-viewer/blob/06fc13e405c36708573a4aeca205e4a0efb3cff7/LICENSE#L1-L21
