### ISSUE TITLE
I tried to use the extension, but...

### ISSUE THREAD

**Issue by StormDragon-64** [mnxn/vscode-jvm-bytecode-viewer#3]
![image](https://user-images.githubusercontent.com/80718549/145336964-b30be0da-ec1a-4318-bfbd-b253c927e6f4.png)
I clicked show bytecode, and nothing happened. I was going to click the extension, but vscode showed some text that said "This extension has reported _1 uncaught error_" I clicked it, and it showed the screenshot I pasted above.

**Comment by mnxn** [comment]
Can you open the developer tools and see if there's anything in the logs there?

Click `Help` at the top of the window then `Toggle Developer Tools`.

**Comment by mnxn** [comment]
You can also check the output logs:
![image](https://user-images.githubusercontent.com/25037249/145338002-eae6c7c0-4cc2-47e9-9e70-90cbc592f327.png)
