### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LandOfChaos** [mnxn/vscode-jvm-bytecode-viewer#4]
An Error Probably JavAP
Descripption i am completly new to java and took me a while to find out that i have to downlode Java JDK (maybe Desribe it better in the description for other beginners) 
Either way i downloded Java JDK 19 (exe file) but it didnt have  Javap.exe so i downloded  the zip and put it manualy in the correct folder 
with that the error code changed to blank

what i was trying to do for the error to happen was to attempt to view an .class that was inside an .jar 

![Screenshot 2023-02-11 221825](https://user-images.githubusercontent.com/125159073/218281693-d13dc6e1-30b1-4616-8eef-84efbb4c0caf.jpg)

![Screenshot 2023-02-11 221636](https://user-images.githubusercontent.com/125159073/218281703-6e3465c4-f953-4134-8665-d46fc76030a6.jpg)

**Comment by mnxn** [comment]
I think `javap` is supposed to be included with any JDK distribution. Where did you download the JDK from?

If you open command prompt or powershell and run `javap -version`, what is the output?

**Comment by LandOfChaos** [comment]
from
https://www.oracle.com/de/java/technologies/downloads/#jdk19-windows

i am currently redownloding trough zip and not the exe because that doesent actualy have javap.exe just the other ones 

and it just errors me when i try to version check

**Comment by mnxn** [comment]
I just used the installer linked on that page and it does have `javap.exe` included.

It is located at `C:\Program Files\Java\jdk-19\bin\javap.exe`. Please make sure `C:\Program Files\Java\jdk-19\bin\` is on your PATH.

**Comment by LandOfChaos** [comment]
Well i missed that completly
so i just added it to path

![grafik](https://user-images.githubusercontent.com/125159073/218282350-66a9aac5-067c-4340-8f6b-db1999a41fba.png)

is it correct

**Comment by LandOfChaos** [comment]
Yep you helped me Adding into the description along the lines of

You have to downlode Jave JDK from the oracle website and add it to your path like that : 

It would help beginners like me who just want to use it to mod game files 

well thank you and have a Nice [enter your timezone] !
