### ISSUE TITLE
viewing jar doesn't seem to work

### ISSUE THREAD

**Issue by SamsTheNerd** [mnxn/vscode-jvm-bytecode-viewer#5]
clicking `Explore Jar File` in any of its locations doesn't seem to do anything. Don't see any messages besides 'Activated' in the extension output or in dev tool output.

Viewing class bytecode works fine though. I'm on MacOS 13.2.1, VSCode version 1.83.0, and javap 17.0.3 if that matters at all. I believe it should be using Java 17. 

Here's the jar i'm trying to view if that helps at all: https://github.com/SamsTheNerd/HexGloop/blob/main/releases/hexgloop-1.19.2-0.1.0b-fabric.jar although it doesn't seem to work with any jar i tested it on, they were also all minecraft mod jar files so if there's some jar specific issue it would probably apply to all of them too.

**Comment by mnxn** [comment]
Are you looking at the `Jar Explorer` side panel? The file listing of the jar file goes there:

![image](https://github.com/mnxn/vscode-jvm-bytecode-viewer/assets/25037249/d531f529-658c-43e2-8af2-bc4876bce7af)

**Comment by mnxn** [comment]
You can also try running the command `Explorer: Focus on Jar Explorer View` in the VS Code Command Palette (Ctrl+Shift+P) to locate it.

**Comment by SamsTheNerd** [comment]
oh ! I didn't realize it was down there, i thought it'd pop up in a new section, my bad !

may be worth it to put a more specific note in the documentation on where that panel actually is, or if possible have it open itself up when you click the `Explore Jar File` ?

thanks for the help though !
